### ISSUE TITLE
queering dimensions throws an exception

### ISSUE THREAD

**Issue by ksobon** [jeremytammik/RevitLookup#32]
I got this when I tried to query Dimensions: 

![image](https://cloud.githubusercontent.com/assets/529781/24160482/5b9d4542-0e38-11e7-9d82-ab4a08f085d6.png)

```
************** Exception Text **************
Autodesk.Revit.Exceptions.InvalidOperationException: Cannot access this method if this dimension has more than one segment.
   at Autodesk.Revit.DB.Dimension.get_LeaderEndPosition()
   at RevitLookup.Snoop.CollectorExts.CollectorExtElement.Stream(ArrayList data, Dimension dim)
   at RevitLookup.Snoop.CollectorExts.CollectorExtElement.Stream(ArrayList data, Element elem)
   at RevitLookup.Snoop.CollectorExts.CollectorExtElement.CollectEvent(Object sender, CollectorEventArgs e)
   at RevitLookup.Snoop.Collectors.Collector.CollectorExt.Invoke(Object sender, CollectorEventArgs e)
   at RevitLookup.Snoop.Collectors.Collector.FireEvent_CollectExt(Object objToSnoop)
   at RevitLookup.Snoop.Collectors.CollectorObj.Collect(Object obj)
   at RevitLookup.Snoop.Forms.Objects.TreeNodeSelected(Object sender, TreeNodeMouseClickEventArgs e)
   at System.Windows.Forms.TreeView.OnNodeMouseClick(TreeNodeMouseClickEventArgs e)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by jeremytammik** [comment]
hi konrad. okay... well, the process to fix it is pretty clear. determine the code snippet throwing the exception and either avoid calling it under the problematic circumstances (better) or catch the specific exception thrown (less good, also ok). can you do that and submit a pull request with the fix, please?

**Comment by ksobon** [comment]
I got this when using the Lookup tool from Revit's UI. I am in no position to debug this particular issue. I know this doesn't exactly make it easy but that's all I got. These seem to be constraint dimensions and I am not sure why they are surfaced in my Revit model. I don't think I should be able to access them. Anyways. That's all I got. Sorry.

**Comment by jeremytammik** [comment]
can you provide a minimal RVT sample? please delete absolutely everything you can except the dimension causing the error. thx!

**Comment by jeremytammik** [comment]
close for now until we have a reproducible case to fix
